# Install Packages

In [ ]:
#Referensi: https://www.linkedin.com/pulse/how-scrape-google-play-reviews-4-simple-steps-using-python-kundi/

!pip install google-play-scraper

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting google-play-scraper
  Downloading google_play_scraper-1.2.3-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.3

In [ ]:
pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nltk in /usr/local/lib/python3.9/dist-packages (3.8.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.9/dist-packages (from nltk) (2022.10.31)
Requirement already satisfied: tqdm in /usr/local/lib/python3.9/dist-packages (from nltk) (4.65.0)
Requirement already satisfied: click in /usr/local/lib/python3.9/dist-packages (from nltk) (8.1.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.9/dist-packages (from nltk) (1.1.1)

# Import Library

In [ ]:
from google_play_scraper import app
import pandas as pd
import numpy as np
import pandas as pd
import string
import nltk
nltk.download()
import re
import spacy
import sys
pd.options.mode.chained_assignment = None

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q

# Scraping

In [ ]:
#Scrape desired number of reviews

from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.microsoft.teams',
    lang='id', # defaults to 'en'
    country='id', # defaults to 'us'
    sort=Sort.NEWEST, # defaults to Sort.MOST_RELEVANT you can use Sort.NEWEST to get newst reviews
    count=5000
)

In [ ]:
df_busu = pd.DataFrame(np.array(result),columns=['review'])

df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))

df_busu.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt
0,46ddce84-7270-42b6-a960-bed26d144d36,Enok Fauzan,https://play-lh.googleusercontent.com/a/AGNmyx...,Selalu loding saat mau meeting,1,0,1416/1.0.0.2023033801,2023-03-04 06:14:49,None,None
1,bdaf4fed-87f5-4f97-9d78-1179c17412da,Bambang Rudyananto,https://play-lh.googleusercontent.com/a-/ACB-R...,Good app,5,0,1416/1.0.0.2023033801,2023-03-03 22:30:29,None,None
2,4d5a5407-0d1e-4ffa-85cf-e5e584adb934,Gatot Ardito,https://play-lh.googleusercontent.com/a/AGNmyx...,Baru mencoba,5,0,1416/1.0.0.2023033801,2023-03-03 08:35:02,None,None
3,cbd65e6c-14be-4201-ab54-b49123606684,Joko Tatang Adiantoro,https://play-lh.googleusercontent.com/a-/ACB-R...,very good,5,0,1416/1.0.0.2023022801,2023-03-03 07:04:07,None,None
4,bf6430bb-3a0c-410e-992c-c1268513d2bd,Ahmad F aqila,https://play-lh.googleusercontent.com/a-/ACB-R...,bagus,5,0,1416/1.0.0.2023033801,2023-03-03 04:11:46,None,None

In [ ]:
len(df_busu.index) #count the number of data we got

5000

In [ ]:
df_busu[['userName', 'score','at', 'content']].head()  #preview userName, rating, date-time, and reviews only

,userName,score,at,content
0,Enok Fauzan,1,2023-03-04 06:14:49,Selalu loding saat mau meeting
1,Bambang Rudyananto,5,2023-03-03 22:30:29,Good app
2,Gatot Ardito,5,2023-03-03 08:35:02,Baru mencoba
3,Joko Tatang Adiantoro,5,2023-03-03 07:04:07,very good
4,Ahmad F aqila,5,2023-03-03 04:11:46,bagus

In [ ]:
#Run This Code to Sort the Data By Date

new_df = df_busu[['userName', 'score','at', 'content']]
sorted_df = new_df.sort_values(by='at', ascending=False) #Sort by Newst, change to True if you want to sort by Oldest.
sorted_df.head()

,userName,score,at,content
0,Enok Fauzan,1,2023-03-04 06:14:49,Selalu loding saat mau meeting
1,Bambang Rudyananto,5,2023-03-03 22:30:29,Good app
2,Gatot Ardito,5,2023-03-03 08:35:02,Baru mencoba
3,Joko Tatang Adiantoro,5,2023-03-03 07:04:07,very good
4,Ahmad F aqila,5,2023-03-03 04:11:46,bagus

In [ ]:
my_df = sorted_df[['userName', 'at', 'content']] #get userName, rating, date-time, and reviews only

In [ ]:
my_df.head()

                userName                  at                         content
0            Enok Fauzan 2023-03-04 06:14:49  Selalu loding saat mau meeting
1     Bambang Rudyananto 2023-03-03 22:30:29                        Good app
2           Gatot Ardito 2023-03-03 08:35:02                    Baru mencoba
3  Joko Tatang Adiantoro 2023-03-03 07:04:07                       very good
4          Ahmad F aqila 2023-03-03 04:11:46                           bagus

In [ ]:
my_df.to_csv("scrape_msteams5000mar.csv", index = False)  #Save the file as CSV , to download: click the folder icon on the left. the csv file should be there.

In [ ]:
data = pd.read_csv("/content/scrape_msteams5000textonly.csv")
data

FileNotFoundError: ignored

In [ ]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>

# Save Data Scrape

In [ ]:
df= pd.read_csv("/content/scrape_msteamsmeijunetext.csv")
df

                                                content
0                                                    ok
1                                                    Ok
2                                                   Oke
3     Need more improvement on the media player... o...
4                                            Bermanfaat
...                                                 ...
1371                               ez to use fitur wah😍
1372      Hebat aplikasinya bisa buat belajar anak saya
1373                                   Apknya bagus bgt
1374                                              bagus
1375          Gak bisa didownload kadang logout sendiri

[1376 rows x 1 columns]